Traceback (most recent call last):
  File "/home/rockefeller/.local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/rockefeller/.local/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/rockefeller/.local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/rockefeller/.local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/rockefeller/.local/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/rockefeller/.local/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/rockefeller/.local/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
xlssource = pd.ExcelFile('books.xlsx')
df = pd.read_excel(xlssource, 'Sheet1')
df
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-12-d3aa16aa49d8>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mxlssource[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mExcelFile[0m[0;34m([0m[0;34m'books.xlsx'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mdf[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_excel[0m[0;34m([0m[0mxlssource[0m[0;34m,[0m [0;34m'Sheet1'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mdf[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.local/lib/python3.9/site-packages/pandas/io/excel/_base.py[0m in [0;36m__init__[0;34m(self, path_or_buffer, engine, storage_options)[0m
[1;32m   1511[0m         [0mself[0m[0;34m.[0m[0mstorage_options[0m [0;34m=[0m [0mstorage_options[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1512[0m [0;34m[0m[0m
[0;32m-> 1513[0;31m         [0mself[0m[0;34m.[0m[0m_reader[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_engines[0m[0;34m[[0m[0mengine[0m[0;34m][0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_io[0m[0;34m,[0m [0mstorage_options[0m[0;34m=[0m[0mstorage_options[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1514[0m [0;34m[0m[0m
[1;32m   1515[0m     [0;32mdef[0m [0m__fspath__[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/.local/lib/python3.9/site-packages/pandas/io/excel/_openpyxl.py[0m in [0;36m__init__[0;34m(self, filepath_or_buffer, storage_options)[0m
[1;32m    546[0m         [0;34m{[0m[0mstorage_options[0m[0;34m}[0m[0;34m[0m[0;34m[0m[0m
[1;32m    547[0m         """
[0;32m--> 548[0;31m         [0mimport_optional_dependency[0m[0;34m([0m[0;34m"openpyxl"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    549[0m         [0msuper[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0m__init__[0m[0;34m([0m[0mfilepath_or_buffer[0m[0;34m,[0m [0mstorage_options[0m[0;34m=[0m[0mstorage_options[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    550[0m [0;34m[0m[0m

[0;32m~/.local/lib/python3.9/site-packages/pandas/compat/_optional.py[0m in [0;36mimport_optional_dependency[0;34m(name, extra, errors, min_version)[0m
[1;32m    169[0m                 [0;32mreturn[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[1;32m    170[0m             [0;32melif[0m [0merrors[0m [0;34m==[0m [0;34m"raise"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 171[0;31m                 [0;32mraise[0m [0mImportError[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    172[0m [0;34m[0m[0m
[1;32m    173[0m     [0;32mreturn[0m [0mmodule[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: Pandas requires version '3.0.7' or newer of 'openpyxl' (version '3.0.0' currently installed).
ImportError: Pandas requires version '3.0.7' or newer of 'openpyxl' (version '3.0.0' currently installed).

